services:
  ecosystem-randomized:
    build:
      context: .
      args:
        INSTALL_EVAL_HD: "true"
        INSTALL_TOOLCHAIN: "true"
        INSTALL_PROTEUS: "true"
    container_name: ecosystem-randomized
    restart: "no"
    stdin_open: true
    tty: true
    working_dir: /ecosystem
    volumes:
      - ./core:/ecosystem/core
      - ./synthesis:/ecosystem/synthesis
      - ./noninterference-testing:/ecosystem/noninterference-testing
      - ./waveform-analysis:/ecosystem/waveform-analysis
      - ./install-scripts:/ecosystem/install-scripts
      - ./formal-verification:/ecosystem/formal-verification
      - ./attacks:/ecosystem/attacks
      - ./scripts:/ecosystem/scripts
      - ./benchmarks:/ecosystem/benchmarks
    command: "/bin/bash"
